name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_42715687
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/sms_teacher/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/uploads/**
            **/con1.php